# Generated by Django 4.2.6 on 2023-10-24 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0003_artists_songs_albums'),
    ]

    operations = [
        migrations.AddField(
            model_name='albums',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='albums',
            name='length',
            field=models.DurationField(default=datetime.timedelta),
        ),
        migrations.AddField(
            model_name='songs',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='songs',
            name='length',
            field=models.DurationField(default=datetime.timedelta),
        ),
    ]
