# Generated by Django 4.2.6 on 2023-10-29 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0008_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='title',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
