# Generated by Django 4.2.6 on 2023-12-02 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0011_remove_reviews_like_reviews_likes_alter_reviews_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='cover_pic'),
        ),
    ]
