# Generated by Django 4.2.6 on 2023-12-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testApp', '0012_songs_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='cover',
            field=models.ImageField(default='default.jpg', upload_to='cover_pic'),
        ),
    ]
